apiVersion: v1
kind: Secret
metadata:
  name: wolfpackcloud-influxdb-secret
  namespace: wolfpackcloud-control
type: Opaque
stringData:
  admin-user: admin
  admin-password: "9c76f7c5f4646e52d4425c6aa50b6bee"
  admin-token: "8b93294490517d04075e83281984b3e99df5635368338fc600e696f9bd5056f5"
