apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wolfpackcloud-influxdb-pvc
  namespace: wolfpackcloud-control
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
