apiVersion: v1
kind: ServiceAccount
metadata:
  name: control-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wolfpackcloud-control-api-nodes-read
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wolfpackcloud-control-api-nodes-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wolfpackcloud-control-api-nodes-read
subjects:
  - kind: ServiceAccount
    name: control-api
    namespace: wolfpackcloud-control
